#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

require_value() {
  local value="$1" label="$2"
  if [[ -z "$value" ]]; then
    printf '  %s✗ %s is required%s\n' "$RED" "$label" "$RESET" >&2
    exit 1
  fi
}

if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  GITHUB_REPOSITORY_URL="$(gh repo view --json url --jq .url 2>/dev/null || true)"
fi
GITHUB_REPOSITORY_URL="${GITHUB_REPOSITORY_URL:-https://github.com}"

banner "Budgetia production setup"

stage "Supabase public client configuration"
say "Only the public project URL and publishable key are written to ignored local files."
open_url "https://supabase.com/dashboard/projects"
step "Open your project, choose Connect, and copy the HTTPS project URL."
ENV_FILE=".env"
ask EXPO_PUBLIC_SUPABASE_URL "Project URL:"
require_value "$EXPO_PUBLIC_SUPABASE_URL" "Project URL"
if [[ ! "$EXPO_PUBLIC_SUPABASE_URL" =~ ^https://[a-z0-9-]+\.supabase\.co/?$ ]]; then
  warn "The URL does not look like a hosted Supabase project URL."
  confirm "Keep this URL anyway?" || exit 1
fi
step "Copy the publishable key (sb_publishable_...) — never a secret/service_role key."
ask EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY "Publishable key:"
require_value "$EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY" "Publishable key"
if [[ "$EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY" =~ ^(sb_secret_|eyJ) ]]; then
  warn "This looks privileged or legacy. Use the modern sb_publishable_ key."
  exit 1
fi
write_env EXPO_PUBLIC_SUPABASE_URL "$EXPO_PUBLIC_SUPABASE_URL"
write_env EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY "$EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY"
ENV_FILE="apps/mobile/.env"
write_env EXPO_PUBLIC_SUPABASE_URL "$EXPO_PUBLIC_SUPABASE_URL"
write_env EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY "$EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY"

stage "GitHub APK configuration"
say "The APK needs the same two public values. GitHub stores them as repository secrets to avoid publishing your project identity in logs."
open_url "${GITHUB_REPOSITORY_URL}/settings/secrets/actions"
set_secret EXPO_PUBLIC_SUPABASE_URL "$EXPO_PUBLIC_SUPABASE_URL"
set_secret EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY "$EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY"

stage "Supabase continuous deployment"
say "Administrative credentials are hidden while typed and sent directly to GitHub. They are never written to .env."
ask SUPABASE_PROJECT_REF "Supabase project ref (the subdomain before .supabase.co):"
require_value "$SUPABASE_PROJECT_REF" "Supabase project ref"
set_var SUPABASE_PROJECT_REF "$SUPABASE_PROJECT_REF"
ask BUDGETIA_WEB_URL "Production web URL without a trailing slash (for example https://account.github.io/budgetia):"
require_value "$BUDGETIA_WEB_URL" "Production web URL"
if [[ ! "$BUDGETIA_WEB_URL" =~ ^https://[^[:space:]]+$ ]]; then
  warn "The production web URL must use HTTPS."
  exit 1
fi
set_var BUDGETIA_WEB_URL "${BUDGETIA_WEB_URL%/}"
set_var SUPABASE_PRODUCTION_ENABLED "false"
if confirm "Configure privileged Supabase CI credentials now?"; then
  open_url "https://supabase.com/dashboard/account/tokens"
  ask_secret SUPABASE_ACCESS_TOKEN "Supabase access token:"
  require_value "$SUPABASE_ACCESS_TOKEN" "Supabase access token"
  ask_secret SUPABASE_DB_PASSWORD "Production database password:"
  require_value "$SUPABASE_DB_PASSWORD" "Production database password"
  set_secret SUPABASE_ACCESS_TOKEN "$SUPABASE_ACCESS_TOKEN"
  set_secret SUPABASE_DB_PASSWORD "$SUPABASE_DB_PASSWORD"
  unset SUPABASE_ACCESS_TOKEN SUPABASE_DB_PASSWORD
  note "Keep SUPABASE_PRODUCTION_ENABLED=false until one manual deployment succeeds."
else
  SKIPPED+=("SUPABASE_ACCESS_TOKEN and SUPABASE_DB_PASSWORD")
fi

stage "Expo EAS signing"
say "EAS is optional for development APKs but required for a Play Store production signing path."
if confirm "Configure an already initialized EAS project now?"; then
  open_url "https://expo.dev/accounts"
  ask EAS_PROJECT_ID "EAS project UUID:"
  require_value "$EAS_PROJECT_ID" "EAS project UUID"
  ask_secret EXPO_TOKEN "Expo access token:"
  require_value "$EXPO_TOKEN" "Expo access token"
  set_var EAS_PROJECT_ID "$EAS_PROJECT_ID"
  ENV_FILE=".env"
  write_env EXPO_PUBLIC_EAS_PROJECT_ID "$EAS_PROJECT_ID"
  ENV_FILE="apps/mobile/.env"
  write_env EXPO_PUBLIC_EAS_PROJECT_ID "$EAS_PROJECT_ID"
  set_var EAS_PRODUCTION_ENABLED "false"
  set_secret EXPO_TOKEN "$EXPO_TOKEN"
  unset EXPO_TOKEN
  if confirm "Enable Expo push access security now?"; then
    step "Create a dedicated Expo access token for push delivery. Do not reuse an OpenAI or Supabase key."
    ask_secret EXPO_PUSH_ACCESS_TOKEN "Expo push access token:"
    require_value "$EXPO_PUSH_ACCESS_TOKEN" "Expo push access token"
    set_secret EXPO_PUSH_ACCESS_TOKEN "$EXPO_PUSH_ACCESS_TOKEN"
    unset EXPO_PUSH_ACCESS_TOKEN
  else
    note "Push delivery remains functional without enhanced Expo access-token security."
  fi
  note "Keep EAS_PRODUCTION_ENABLED=false until an interactive preview build succeeds."
else
  SKIPPED+=("EAS project, EXPO_TOKEN and first interactive preview build")
fi

stage "Manual production gates"
say "Secrets are configured, but production remains deliberately disabled until these external checks pass."
step "Enable GitHub Pages with GitHub Actions; web-pages.yml deploys /oauth/consent automatically."
step "The Supabase production workflow enables OAuth with BUDGETIA_WEB_URL; configure email confirmations and production SMTP separately."
step "Run the Supabase production workflow manually, inspect it, then set SUPABASE_PRODUCTION_ENABLED=true."
step "Install the exact GitHub APK on a physical Android device and test two accounts plus a shared budget."
step "Run a silent tracked-file and Git-history secret audit before tagging a release."
if git ls-files | grep -E '(^|/)(\.env($|\.)|.*\.(jks|keystore|p12|pem)$)' >/dev/null; then
  warn "A tracked credential-like filename was found. Review git ls-files before continuing."
else
  printf '  %s✓ no tracked .env or signing-key filename found%s\n' "$GREEN" "$RESET"
fi

finish
